# Generated by Django 4.2.7 on 2026-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pendingregistration_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
