# Generated by Django 4.2.7 on 2026-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_pendingregistration_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
