# Generated by Django 4.2.7 on 2026-09-06 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_merge_20260826_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
