# Generated by Django 4.2.7 on 2026-08-29 12:21

from django.db import migrations, models


def preserve_existing_attempt_timestamps(apps, schema_editor):
    QuizAttempt = apps.get_model('quiz', 'QuizAttempt')

    for attempt in QuizAttempt.objects.all().iterator():
        attempt.started_at = attempt.submitted_at
        attempt.updated_at = attempt.submitted_at
        attempt.save(
            update_fields=[
                'started_at',
                'updated_at',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(
                choices=[
                    ('IN_PROGRESS', 'IN_PROGRESS'),
                    ('SUBMITTED', 'SUBMITTED'),
                ],
                default='SUBMITTED',
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
            ),
        ),

        migrations.AddField(
            model_name='quizattempt',
            name='updated_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
            ),
        ),

        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),

        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(
                null=True,
                blank=True,
            ),
        ),

        migrations.RunPython(
            preserve_existing_attempt_timestamps,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),

        migrations.AlterField(
            model_name='quizattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
            ),
        ),

        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(
                fields=('attempt', 'question'),
                name='unique_answer_per_attempt_question',
            ),
        ),
    ]