# Generated by Django 4.2.7 on 2026-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_add_resume_attempt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('SUBMITTED', 'SUBMITTED')], default='IN_PROGRESS', max_length=20),
        ),
    ]
