from .schemas import ProcessedDocument


def build_summarization_content(
    document: ProcessedDocument,
) -> str:
    """
    Convert a processed document into ordered textual content
    ready to be sent to the summarization service.

    Sources:
        element.text
            Native text extracted directly from the document.

        element.visible_text
            Text extracted from images using OCR.

        element.description
            Visual explanation generated by Qwen3-VL.

        element.relationships
            Visual relationships generated by Qwen3-VL.

    The original page and element order is preserved.
    """

    output_parts = []

    for unit in document.get_ordered_units():

        page_parts = []

        # =====================================================
        # Page header
        # =====================================================

        page_parts.append(
            f"\n===== PAGE {unit.index} ====="
        )

        # =====================================================
        # Elements in original order
        # =====================================================

        for element in unit.get_ordered_elements():

            # -------------------------------------------------
            # Native text
            # -------------------------------------------------

            if element.type == "text":

                text = _clean_text(
                    element.text
                )

                if text:
                    page_parts.append(text)

                continue

            # -------------------------------------------------
            # Image content
            # -------------------------------------------------

            if element.type == "image":

                image_content = (
                    _build_image_content(
                        element
                    )
                )

                if image_content:
                    page_parts.append(
                        image_content
                    )

        # =====================================================
        # Add page only if it contains content
        # =====================================================

        if len(page_parts) > 1:

            output_parts.extend(
                page_parts
            )

    return "\n\n".join(
        output_parts
    ).strip()


def _build_image_content(
    element,
) -> str:
    """
    Build textual representation of one image.
    """

    parts = []

    # =========================================================
    # OCR visible text
    # =========================================================

    visible_text = [
        _clean_text(text)
        for text in (
            element.visible_text or []
        )
        if _clean_text(text)
    ]

    if visible_text:

        parts.append(
            "[TEXT INSIDE IMAGE]"
        )

        parts.append(
            "\n".join(
                visible_text
            )
        )

    # =========================================================
    # Visual description from Qwen
    # =========================================================

    description = _clean_text(
        element.description
    )

    if description:

        parts.append(
            "[VISUAL DESCRIPTION]"
        )

        parts.append(
            description
        )

    # =========================================================
    # Visual relationships
    # =========================================================

    relationships = [
        _clean_text(relation)
        for relation in (
            element.relationships or []
        )
        if _clean_text(relation)
    ]

    if relationships:

        parts.append(
            "[VISUAL RELATIONSHIPS]"
        )

        for relationship in relationships:

            parts.append(
                f"- {relationship}"
            )

    if not parts:
        return ""

    return "\n".join(
        parts
    )


def _clean_text(
    text: str | None,
) -> str:
    """
    Basic text cleanup without changing
    the educational meaning.
    """

    if not text:
        return ""

    text = (
        str(text)
        .replace("\x00", "")
        .replace("\u0000", "")
        .strip()
    )

    return text